server.port=8090

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/wispnote
spring.datasource.username=${POSTGRES_USERNAME:wispnote}
spring.datasource.password=${POSTGRES_PASSWORD:wispnote}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

## Flyway Configuration
spring.flyway.enabled=true

## Access Token Signing Key
rsa.access-token.private-key=${ACCESS_TOKEN_PRIVATE_KEY:classpath:keys/access-token.pem}
rsa.access-token.public-key=${ACCESS_TOKEN_PUBLIC_KEY:classpath:keys/access-token.pub}

## Refresh Token Signing Key
rsa.refresh-token.private-key=${REFRESH_TOKEN_PRIVATE_KEY:classpath:keys/refresh-token.pem}
rsa.refresh-token.public-key=${REFRESH_TOKEN_PUBLIC_KEY:classpath:keys/refresh-token.pub}

# Messaging
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
spring.rabbitmq.connection-timeout=5s
