spring.application.name=wispnote-backend
server.shutdown=graceful

logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

# JPA
spring.jpa.open-in-view=false

# JSON
spring.jackson.default-property-inclusion=non_null

## Flyway Configuration
spring.flyway.enabled=false

# Messaging
message-publisher.provider=${MESSAGE_PUBLISHER_PROVIDER:rabbitmq}
message-publisher.notes-exchange=wispnote.notes
message-publisher.analyzer-queue=wispnote.notes.analyzer
spring.rabbitmq.publisher-confirm-type=correlated
spring.rabbitmq.publisher-returns=true