server.port=8090

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/wispnote
spring.datasource.username=${POSTGRES_USERNAME:wispnote}
spring.datasource.password=${POSTGRES_PASSWORD:wispnote}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
