spring.application.name=wispnote-backend
server.shutdown=graceful

logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

# JPA
spring.jpa.open-in-view=false

# JSON
spring.jackson.default-property-inclusion=non_null

## Flyway Configuration
spring.flyway.enabled=false